url: str = r"https://kadbase.ru/"
auth_url: str = r"https://kadbase.ru/lk/"
login: str = ""
password: str = ""
excel_output_file_name: str = r"C:\Users\yunas\OneDrive\Рабочий стол\Parser\addresses_out.xlsx"
excel_input_file_name: str = r"C:\Users\yunas\OneDrive\Рабочий стол\Parser\addresses.xlsx"